# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test-shasta:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: '8'
    - name: Verify Java
      run: java -version
    - name: Install Cromwell and Womtool
      run: |
          wget https://github.com/broadinstitute/cromwell/releases/download/58/cromwell-58.jar
          wget https://github.com/broadinstitute/cromwell/releases/download/58/womtool-58.jar
    - name: Verify Cromwell and Womtool
      run: |
          java -jar cromwell-58.jar --version
          java -jar womtool-58.jar --version
    - name: Validate wdl with Womtool
      run: java -jar womtool-58.jar validate MitoHiFi.wdl
    - name: Run wdl with Cromwell
      run: java -jar cromwell-58.jar run MitoHiFi.wdl -i MitoHiFi.json
